### ISSUE TITLE
[BUG]: robotpy not installing properly

### ISSUE THREAD

**Issue by bdmiller42** [robotpy/robotpy-docs#68]
### Problem description

Tried to upgrade from 2023 to 2024. Followed the instructions in the documentation. Each time I try to run robot py I get the following as an error message from what I assume to be the package itself. I upgraded pip to the current version running python 3.11

```
C:\Users\KHSRo>py -3 -m robotpy
Traceback (most recent call last):
  File "C:\Users\KHSRo\AppData\Local\Programs\Python\Python311\Lib\site-packages\robotpy\main.py", line 245, in main
    cmd_class = entry_point.load()
                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\KHSRo\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KHSRo\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\KHSRo\AppData\Local\Programs\Python\Python311\Lib\site-packages\robotpy_installer\cli_deploy.py", line 18, in <module>
    from . import pypackages, pyproject, roborio_utils, sshcontroller
  File "C:\Users\KHSRo\AppData\Local\Programs\Python\Python311\Lib\site-packages\robotpy_installer\pypackages.py", line 10, in <module>
    from packaging.metadata import Metadata
ModuleNotFoundError: No module named 'packaging.metadata'
Plugin error detected in 'EntryPoint(name='deploy', value='robotpy_installer.cli_deploy:Deploy', group='robotpy')' (use --ignore-plugin-errors to ignore this)
```

### Operating System

Windows

### Installed Python Packages

```text
Package                  Version
------------------------ ----------
attrs                    22.2.0
bcrypt                   4.0.1
cffi                     1.15.1
click                    8.1.3
colorama                 0.4.6
comtypes                 1.1.14
cryptography             39.0.0
iniconfig                2.0.0
numpy                    1.24.2
opencv-python            4.7.0.72
packaging                23.0
paramiko                 2.12.0
Pint                     0.20.1
pip                      23.3.2
pluggy                   1.0.0
pycparser                2.21
pyfrc                    2024.0.1
pygrabber                0.1
PyNaCl                   1.5.0
pynetconsole             2.0.4
pynetworktables          2021.0.0
pyntcore                 2024.1.1.1
pytest                   7.2.0
pytest-reraise           2.1.2
robotpy                  2024.1.1.3
robotpy-cli              2024.0.0
robotpy-cscore           2023.4.3.0
robotpy-hal              2024.1.1.1
robotpy-halsim-gui       2024.1.1.1
robotpy-installer        2024.1.0
robotpy-rev              2023.1.3.2
robotpy-wpilib-utilities 2024.0.0
robotpy-wpimath          2024.1.1.1
robotpy-wpinet           2024.1.1.1
robotpy-wpiutil          2024.1.1.1
setuptools               65.5.0
six                      1.16.0
tomli                    2.0.1
wpilib                   2024.1.1.1
```

### Reproducible example code

```text
> py -3 -m robotpy
```

**Comment by virtuald** [comment]
`pip install -U packaging` should do the trick. Sorry about that, will update the dependencies tonight.
